bankApp/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/users/login')),
    path('admin/', admin.site.urls),
    path('accounts/', include('bank_accounts.urls')),
    path('investments/', include('investments.urls')),
    path('users/', include('users.urls')),
    path('django-rq/', include('django_rq.urls')),
    #Api urls--
    path('api/v1/users/', include('users.endpoints')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank_accounts/urls.py
from django.urls import path

from . import views



app_name = "bank_accounts"

urlpatterns = [
   path('', views.accounts_index, name='accounts_index'),
   path('loans/', views.loan_index, name='loan_index'),
   path('create_account/', views.create_account, name='create_account'),
   path('create_savings/', views.create_savings, name='create_savings'),
   path('account/<int:id>', views.accounts_show, name='accounts_show'),
   path('transactions/create', views.transactions_create, name='transactions_create'),
   path('transactions/createLoan', views.create_loan, name='create_loan'),
   path('transactions/payLoan', views.pay_loan, name='pay_loan'),
   path('transactions', views.transactions_store, name='transactions_store'),

]

users/urls.py
from django.urls import path

from . import views

app_name='users'

urlpatterns = [
    path('', views.users, name='users'),
    path('<int:id>/', views.user, name='user'),
    path('<int:id>/profile', views.user_profile, name='user_profile'),
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

bank_accounts/models.py
from django.db import models
from djmoney.money import Money
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(default = 'Main account', max_length=250)
    accountType = models.CharField(default='checking', max_length=250)
    
    @classmethod
    def find_by_id(cls, id):
        return cls.objects.get(pk=id)

    @classmethod
    def get_accounts(cls, user):
        return cls.objects \
            .annotate(balance=models.functions.Coalesce(
                models.Sum('transaction__amount'), 0)
            ) \
            .filter(user=user) \
            .filter(balance__gte=0)

    @classmethod
    def get_loans(cls, user):
        return cls.objects \
            .annotate(balance=models.Sum('transaction__amount')) \
            .filter(user=user) \
            .filter(balance__lt=0)

    
    @classmethod
    def get_savings(cls, user):
        return cls.objects \
            .annotate(balance=models.Sum('transaction__amount')) \
            .filter(user=user) \
            .filter(accountType='savings') 
            


    def get_balance(self):
        balance = self.transaction_set \
            .aggregate(models.Sum('amount')) \
            .get('amount__sum') or 0
        return Money(balance, 'USD')

    def __str__(self):
        return f'{self.name} Account'

class Transaction(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency='USD'
    )
    interacting_account = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        related_name='interacting_account',
        null=True
    )
    area = models.CharField(default='transfer', max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def create(cls, from_account, to_account, amount, area):
        from_transaction = cls()
        from_transaction.account_id = from_account.id
        from_transaction.interacting_account_id = to_account.id
        from_transaction.amount = -amount
        from_transaction.area = area
        from_transaction.save()

        to_transaction = cls()
        to_transaction.account_id = to_account.id
        to_transaction.interacting_account_id = from_account.id
        to_transaction.amount = amount
        to_transaction.area = area
        to_transaction.save()

    @classmethod
    def create_to_bank(cls, account, amount, area):
        transaction = cls()

        transaction.account_id = account.id
        transaction.amount = -amount
        transaction.area = area

        transaction.save()

        return transaction

    @classmethod
    def create_from_bank(cls, account, amount, area):
        transaction = cls()

        transaction.account_id = account.id
        transaction.amount = amount
        transaction.area = area

        transaction.save()

        return transaction

bank_accounts/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from djmoney.money import Money
from django.contrib.auth.models import User
from .models import Account, Transaction
from django.http import HttpResponseRedirect
import django_rq
from django.db.models import Q
from bank_accounts.jobs import create_transaction
from operator import attrgetter
from math import ceil
from django.contrib import messages


# @login_required(login_url='/users/login/')
def accounts_index(request):
    accounts = Account.get_accounts(request.user)
    accounts_count = Account.get_accounts(request.user).count()
    context = {
        "accounts_count":accounts_count,
        "usersAccounts": Account.get_accounts(request.user)
    }
    query = ""

    
    if request.GET:
        query = request.GET['q']
        context['query'] = str(query)

    accounts = sorted(get_Bankaccount_search(request, query), key=attrgetter('name'), reverse=True)
    context['accounts'] = accounts
    return render(request, 'bank_accounts/accounts/index.html', context )

def loan_index(request):
    loans = Account.get_loans(request.user)
    
    context = {
        "loans" : loans,
    }
    
    
    return render(request, 'bank_accounts/accounts/loans.html', context)


# @login_required(login_url='/users/login/')
def accounts_show(request, id):
    account = Account.objects.get(id=id)
   
    return render(request, 'bank_accounts/accounts/show.html', {
        'account': account,
        'balance': account.get_balance(),
        'transactions': account.transaction_set.all()
    })

# @login_required(login_url='/users/login/')
def create_account(request):
    context = {
        'users': User.objects.all()
    }

    if request.method == "POST":
      account = Account()
      name = request.POST['name']
      account.user = request.user
      account.name = name
      account.save()

      return HttpResponseRedirect(reverse('bank_accounts:accounts_index'))

    
    return render(request, 'bank_accounts/accounts/createAccount.html', context)

# @login_required(login_url='/users/login/')
def create_savings(request):
    accounts = Account.get_savings(request.user).count()
    context = {}

    if request.method == "POST":
        account = Account()
        name = request.POST['name']
        account.user = request.user
        account.name = name
        account.accountType = 'savings'
        account.save()

        return HttpResponseRedirect(reverse('bank_accounts:accounts_index'))

    
    return render(request, 'bank_accounts/accounts/createSavings.html', context)

def delete_account(request, id):
    pass


def get_Bankaccount_search(request, query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        bankAccountObj = Account.objects.filter(Q(name__icontains=q)).distinct()
        for account in bankAccountObj:
            queryset.append(account)
    return list(set(queryset))


# @login_required(login_url='/users/login/')
def transactions_create(request):
    return render(request, 'bank_accounts/transactions/create.html', {
        'accounts': Account.get_accounts(request.user),
        'allAccounts' : Account.objects.all()
    })

# @login_required(login_url='/users/login/')
def transactions_store(request):
    if not request.method == 'POST':
        return 

    errors = []

    if not request.POST.get('from'):
        errors.append('From must be set')

    if not request.POST.get('to'):
        errors.append('To must be set')

    if not request.POST.get('amount'):
        errors.append('Amount must be set')

    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)

        return render(request, 'bank_accounts/transactions/create.html')
    
    amount = Money(request.POST.get('amount'), 'USD')
    from_account = Account.objects.get(id=request.POST.get('from'))
    to_account = Account.objects.get(id=request.POST.get('to'))
    area = 'Transfer'

    if not from_account.user.id == request.user.id:
        errors.append('You can only transfer money from your own account')

    if amount < Money(0, 'USD'):
        errors.append('Amount must be more than 0')

    if from_account.get_balance() < amount:
        errors.append('You don\'t have enough funds')

    if len(errors) > 0:
        for error in errors:
            messages.error(request, error)

        return render(request, 'bank_accounts/transactions/create.html')

    recipient_savings_accounts = Account.get_savings(to_account.user)

    if len(recipient_savings_accounts) > 0:
        if amount > Money(0, 'USD'):
            savings_percentage = 0.02 # Save 2%
            savings_amount_per_account = amount * savings_percentage
            total_savings_amount = len(recipient_savings_accounts) * savings_amount_per_account
            amount = amount - total_savings_amount

            for account in recipient_savings_accounts:
                request.user.userprofile.deposit_savings(from_account, account, savings_amount_per_account, area)

    create_transaction(from_account, to_account, amount, area)

    return redirect('bank_accounts:accounts_index')



def create_loan(request):
    context = {
        "accounts": Account.get_accounts(request.user)
    }

    if request.method == 'POST':
        amount = Money(request.POST.get('amount'), 'USD')
        name = request.POST['name']
        to_account = Account.objects.get(id=request.POST.get('to'))
        if request.user.userprofile.loan_check:
            if to_account.get_balance() > Money(0, 'USD'):
                return render(request, 'bank_accounts/transactions/createLoan.html', {
                'error': 'Your account has funds on it already!'
            })
            else:
                request.user.userprofile.make_loan(amount,to_account ,name)
        else:
            messages.error(request, 'You don\'t have the correct rank')
        return HttpResponseRedirect(reverse('bank_accounts:accounts_index'))
    else:

        return render(request, 'bank_accounts/transactions/createLoan.html', context)

def pay_loan(request):
    context = {
        "accounts": Account.get_accounts(request.user),
        "loans": Account.get_loans(request.user)
    }
    if request.method == 'POST':
        from_account = Account.objects.get(id=request.POST.get('from'))
        to_loan = Account.objects.get(id=request.POST.get('to'))
        amount = to_loan.get_balance()
        area = 'Loan payback'
        if to_loan.get_balance() > Money(0, 'USD'):
                return render(request, 'bank_accounts/transactions/payLoan.html', {
                'error': 'Balance is not negative on loan!'
            })
        else:
            request.user.userprofile.pay_loan(amount, from_account, to_loan, area)
        return HttpResponseRedirect(reverse('bank_accounts:accounts_index'))
    else:

        return render(request, 'bank_accounts/transactions/payLoan.html', context)

bank_accounts/templates/bank_accounts/accounts/createAccount.html
{% extends "users/base.html" %}

{% block content %}
    <div class="content-section">
        <h3>Create an account</h3>
        <form action="{% url 'bank_accounts:create_account' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Account name">
            
           
            <button>Create</button>
         </form>
         
         <hr />
         {% if error %}
            {{ error }}
         {% endif %}
    </div>
{% endblock content %}

bank_accounts/templates/bank_accounts/accounts/createSavings.html
{% extends "users/base.html" %}

{% block content %}
    <div class="content-section">
        <h3>Create an savings account</h3>
        <form action="{% url 'bank_accounts:create_savings' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Account name">
            
           
            <button>Create</button>
         </form>
         
         <hr />
         {% if error %}
            {{ error }}
         {% endif %}
    </div>
{% endblock content %}

bank_accounts/templates/bank_accounts/accounts/index.html
{% extends 'users/base.html' %}  
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h2>Accounts overview</h2>


                {% for account in usersAccounts %}
                    <li class="list-group-item">
                        <a href="{% url 'bank_accounts:accounts_show' account.id %}" class="list-group-item list-group-item-action">
                            {{ account.name }} ({{ account.accountType }})
                        </a>
                    </li>
                    {% endfor %}
                    <a href="{% url 'bank_accounts:transactions_create' %}" class="btn btn-dark">
                    Transfer money
                    </a>
            </div>
        </div>
    </div>
{% endblock %}

bank_accounts/templates/bank_accounts/accounts/loans.html
{% extends 'users/base.html' %}
{% block content %}
<div class="col-sm-6">
    <h2>Loans</h2>
      
    <div class="card" style="width: 18rem;">
        <ul class="list-group list-group-flush">
            {% for loan in loans %}
          <li class="list-group-item"><a href="{% url 'bank_accounts:accounts_show' loan.id %}" class="list-group-item list-group-item-action">
            {{ loan.name }}
        </a></li>
            {% endfor %}
        </ul>
      </div>
    <br>
    <a href="{% url 'bank_accounts:create_loan' %}" class="btn btn-dark">
        make a loan
    </a>
</div>
{% endblock %}

bank_accounts/templates/bank_accounts/accounts/show.html
{% extends 'users/base.html' %} 

{% block head %}
<title>{{ account.name }}</title>
{% endblock %} 

{% block content %}
<div class="container">
    <h1>{{ account.name }} ({{ account.accountType }})</h1>

    <div class="card" style="width: 20rem;">
        <div class="card-body">
            <span>Balance:</span>
            {% load djmoney %}
            <span>{% money_localize balance %}</span>
        </div>
    </div>


    <h2>History</h2>
    <div class="card" style="width: 20rem;">
        <div class="card-body" id="transactionDiv">
            <ul>
                {% for transaction in transactions %}
                <li>
                    <div>
                        <span>Amount:</span>
                        <span>{{ transaction.amount }}</span>
                    </div>
                    {% if transaction.is_outgoing %}
                    <div>
                        <span>To:</span>
                        <span>
                            {{ transaction.interacting_account.name }}
                            ({{transaction.interacting_account.id }})
                        </span>
                    </div>
                    {% else %}
                    <div>
                        <span>From:</span>
                        <span>
                            {{ transaction.interacting_account.name }}
                            ({{transaction.interacting_account.id }})
                        </span>
                    </div>
                    {% endif %}
                    <div>
                        <span>Date:</span>
                        <span>{{ transaction.created_at | date:"d/m/Y" }}</span>
                    </div>
                </li>
                <hr>
                {% endfor %}
            </ul>
            
        </div>
        
    </div>
    <br>
    <div class="row">
        <div class="container">
            <a class="btn btn-dark" href="{% url 'bank_accounts:transactions_create' %}">Transfer money</a>
            
            <a class="btn btn-outline-danger" href="{% url 'bank_accounts:pay_loan' %}">Pay back</a>
            
        </div>
    </div>
</div>
{% endblock %}