bankApp/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/users/login')),
    path('admin/', admin.site.urls),
    path('accounts/', include('bank_accounts.urls')),
    path('investments/', include('investments.urls')),
    path('users/', include('users.urls')),
    path('django-rq/', include('django_rq.urls')),
    #Api urls--
    path('api/v1/users/', include('users.endpoints')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank_accounts/urls.py
from django.urls import path

from . import views



app_name = "bank_accounts"

urlpatterns = [
   path('', views.accounts_index, name='accounts_index'),
   path('loans/', views.loan_index, name='loan_index'),
   path('create_account/', views.create_account, name='create_account'),
   path('create_savings/', views.create_savings, name='create_savings'),
   path('account/<int:id>', views.accounts_show, name='accounts_show'),
   path('transactions/create', views.transactions_create, name='transactions_create'),
   path('transactions/createLoan', views.create_loan, name='create_loan'),
   path('transactions/payLoan', views.pay_loan, name='pay_loan'),
   path('transactions', views.transactions_store, name='transactions_store'),

]

investments/urls.py
from django.urls import path

from . import views


app_name = "investments"

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('stocks/<str:ticker>', views.stock, name='stock'),
    path('stocks/<str:ticker>/buy', views.BuyView.as_view(), name='buy'),
    path('stocks/<str:ticker>/sell-all', views.SellAllView.as_view(), name='sell_all'),
    path('stocks/<str:ticker>/sell/<int:investment_id>', views.SellView.as_view(), name='sell'),
]

users/urls.py
from django.urls import path

from . import views

app_name='users'

urlpatterns = [
    path('', views.users, name='users'),
    path('<int:id>/', views.user, name='user'),
    path('<int:id>/profile', views.user_profile, name='user_profile'),
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

users/models.py
from django.db import models
from bank_accounts.models import Account, Transaction
import random
from django.conf import settings
from django.contrib.auth.models import User
import django_rq
from django.dispatch import receiver
from django.db.models.signals import post_save

from bank_accounts.jobs import create_transaction


class UserRank(models.Model):
    name = models.CharField(max_length=35, unique=True)
    value = models.IntegerField(unique=True)

    @classmethod
    def find_by_id(cls, id):
        return cls.objects.get(pk=id)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phoneNumber = models.CharField(default='52525', max_length=10)
    userRank = models.ForeignKey(UserRank, on_delete=models.PROTECT)  
    
    @classmethod
    def create_customer(cls, username, password, email, phone, rankId) -> User:
        user = User.objects.create_user(username=username, password=password, email=email)
        rank = UserRank.find_by_id(rankId)
        print(f"@@@@@@@@@@ {rankId}")
        print(f"!!!!!!!!!! {rank}")

        profile = cls()

        profile.user = user
        profile.userRank = rank
        profile.phoneNumber = phone

        profile.save()

        return user

    @property
    def loan_check(self) -> bool:
        return self.userRank.value >= settings.CUSTOMER_RANK_LOAN
    
    @property
    def did_payback(self) -> bool:
        return self.userRank.value >= settings.CUSTOMER_RANK_LOAN
    
    def make_loan(self, amount, to_account, name):
        assert self.loan_check, 'User membership rank not high enough!'
        loan = Account(user=self.user, name=f'{name}')
        loan.save()
        create_transaction(loan, to_account, amount, 'loan')

    def pay_loan(self, amount, from_account, to_loan, area): 
        create_transaction(to_loan, from_account, amount, area)

    def deposit_savings(self, from_account, savings_account, amount, area):
        create_transaction(from_account, savings_account, amount, area)
    
    def __str__(self):
        return f'{self.user.username} UserProfile'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['userRank']

users/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from .models import User, UserProfile, UserRank
from bank_accounts.models import Account
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from django.db.models import Q
from djmoney.money import Money
from django.contrib import messages


def users(request):
    # if not request.user.is_superuser:
    #     return HttpResponseRedirect(reverse('users:home'))

    return render(request, 'users/users.html')

def profile(request):
    context = {
        'users': User.objects.filter(pk=request.user.id),
        'accounts': Account.get_savings(request.user)
    }

    return render(request, 'users/profile.html',context)

def user(request, id):
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('users:home'))

    customer = get_object_or_404(User, pk=id)
    context = {
        'accounts': Account.objects.filter(user_id=id).all(),
        "userRanks": UserRank.objects.all(),
        "customer": customer
    }
    if request.method == "POST":
        userRank = request.POST['userRank']
        customer.userRank = get_object_or_404(UserRank, id=userRank)
        customer.save()
        return HttpResponseRedirect(reverse('users:home'))
    return render(request, 'users/user.html', context)

def user_profile(request, id):
    if not request.method == "POST":
        return HttpResponseRedirect(reverse('users:home'))

    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('users:home'))

    user = User.objects.get(pk=id)
    rankId = request.POST.get('rank')
    rank = UserRank.find_by_id(rankId)

    user.userprofile.userRank = rank
    user.userprofile.save()

    messages.success(request, 'Rank updated')

    return HttpResponseRedirect(reverse('users:users'))


def home(request):
    context = {
        'users': User.objects.all()
    }

    return render(request, 'users/home.html', context)


def login(request):
    contex={}

    if request.method == 'POST':
        user = authenticate(request, username= request.POST['username'], password = request.POST['password'] )
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('users:home'))
        else:
            contex={'error':'Bad username or password'}
    return render(request,'users/login.html',contex)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('users:login'))

def register(request):
    if not request.user.is_superuser:
        return HttpResponseRedirect(reverse('users:home'))

    context = {
       "userRanks": UserRank.objects.all()
    }

    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user_name = request.POST['username']
        email = request.POST['email']
        phone = request.POST['phone']
        rank = request.POST['rank']

        if password == confirm_password:
            user = UserProfile.create_customer(user_name, password, email, phone, rank)
            if user:
                return HttpResponseRedirect(reverse('users:users'))
            else:
                context = {
                    'error': 'Could not create user account - please try again.'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again.',
            }
    return render(request, 'users/create_user.html', context)

users/templates/users/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="/docs/4.1/assets/img/favicons/favicon.ico">

    <title>GetBroke</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'main.css' %}" type="text/css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">GetBroke</a>
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          {% if user.is_authenticated %}
          <a class="nav-link" href="{% url 'users:logout' %}">Logout <span data-feather="log-out"></a>
          
          {% else %}
          <a class="nav-link" href="{% url 'users:login' %}">Log in <span data-feather="log-in"></a>
          {% endif %}
        </li>
       
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky" id="sideBar">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link {% if '/users/home/' in request.path %}active{% endif %}" href="{% url 'users:home' %}">
                  <span data-feather="home"></span>
                  Home
                </a>
              </li>

              <li class="nav-item">
                {% if user.is_authenticated and user.is_superuser %}
                <a class="nav-link {% if '/users/' == request.path %}active{% endif %}" href="{% url 'users:users' %}">
                  <span data-feather="grid"></span>
                  Users
                </a>
                {% endif %}
              </li>
              <li class="nav-item">
                <a class="nav-link {% if '/accounts/' == request.path %}active{% endif %}" href="{% url 'bank_accounts:accounts_index' %}">
                  <span data-feather="dollar-sign"></span>
                  Accounts
                </a>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link {% if '/accounts/loans/' in request.path %}active{% endif %}" href="{% url 'bank_accounts:loan_index' %}">
                  <span data-feather="home"></span>
                  Loans <span class="sr-only">(current)</span>
                  
                <a class="nav-link {% if '/investments/' in request.path %}active{% endif %}" href="{% url 'investments:dashboard' %}">
                  <span data-feather="bar-chart"></span>
                  Investments
                </a>
                {% endif %}
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                  <a class="nav-link {% if '/users/profile/' in request.path %}active{% endif %}" href="{% url 'users:profile' %}">
                    <span data-feather="users"></span>
                    My profile
                  </a>
                {% endif %}
              </li>
            </ul>

          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          
          {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            {% block content %}
            {% endblock %}
          </div>

          

          
          
        </main>
      </div>
    </div>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
      // Get the container element
      var btnContainer = document.getElementById("sideBar");

// Get all buttons with class="btn" inside the container
      var btns = btnContainer.getElementsByClassName("nav-link");

// Loop through the buttons and add the active class to the current/clicked button
      for (var i = 0; i < btns.length; i++) {
        btns[i].addEventListener("click", function() {
          var current = document.getElementsByClassName("nav-link active");
          current[0].className = current[0].className.replace(" active", " ");
          this.className += " active";
        });
      }
    </script>
   
   
    
  </body>
</html>

users/templates/users/create_user.html
{% extends "users/base.html" %}

{% block content %}
    <div class="content-section">
        <form action="{% url 'users:register' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input class="form-control" type="text" name="username" placeholder="User Name">
            <br>
            <input class="form-control" type="email" name="email" placeholder="Email Address">
            <br>
            <input class="form-control" type="tel" name="phone" placeholder="Phone">
            <br>
            <input class="form-control" type="password" name="password" placeholder="Password">
            <br>
            <input class="form-control" type="password" name="confirm_password" placeholder="Confirm Password">
            <br>
            <select name="rank">
                {% for rank in userRanks %}
                    <option value="{{ rank.id }}" {% if rank.id == 1 %}selected{% endif %}>
                        {{ rank.name }}
                    </option>
                {% endfor %}
            </select>

            
            <button class="btn btn-primary btn-block py-2 my-3">Create customer</button>
         </form>
         <hr />
         {% if error %}
            {{ error }}
         {% endif %}
    </div>
{% endblock content %}

users/templates/users/home.html
{% extends "users/base.html" %}
{% block content %}
<div class="container">
    <div class="row no-gutters">
        <h2>Welcome to the GetBroke bank {{request.user.username}}!</h2>
        <br>
        <a class="btn btn-dark" href="{% url 'bank_accounts:create_account' %}" role="button">
            Open account
        </a>
    </div>
</div>
    
{% endblock content %}

users/templates/users/login.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form action="{% url 'users:login' %}" method="POST">
            {% csrf_token %}
            <input class="form-control" type="text" placeholder="username" name="username">
            <br>
            <input class="form-control" type="password" placeholder="password" name="password">
            <br>
            <input class="btn btn-primary btn-block py-2 my-3" type="submit" value="Login">
        </form>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'users/base.html' %} 

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 mb-4">
            <h2>Profile overview</h2>
            <div>
                <div class="card">
                    <div class="card-body">
                        <form id="user-info-form">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="text" id="username-field" class="form-control" name="username" value="{{ user.username }}">
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" id="email-field" class="form-control" name="email" value="{{ user.email }}">
                            </div>
                            <button class="btn">Update</button>
                        </form>
                        <hr>
                        <div>
                            <span>Rank:</span>
                            <h3>{{ user.userprofile.userRank.name }}</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <h2>Savings Account</h2>
            {% for account in accounts %}
                <div class="card text-white bg-dark mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Name: {{account.name}}</h5>
                        <hr>
                        <a href="{% url 'bank_accounts:accounts_show' account.id %}" class="btn btn-light">View</a>
                    </div>
                </div>
            {% endfor %}
            <a class="btn btn-dark" href="{% url 'bank_accounts:create_savings' %}">Open savings account</a>
        </div>
    </div>
</div>

<script>
    const endpoint = "/api/v1/users/{{ user.id }}"
    const form = document.querySelector('#user-info-form')
    const usernameField = document.querySelector('#username-field')
    const emailField = document.querySelector('#email-field')

    function getCookie(name) {
        let cookieValue = null
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';')
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim()
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === name + '=') {
                    cookieValue = decodeURIComponent(
                        cookie.substring(name.length + 1)
                    )
                    break
                }
            }
        }
        return cookieValue
    }

    const updateUser = async data => {
        const response = await fetch(endpoint, {
            method: 'PATCH',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCookie('csrftoken')
            },
            body: JSON.stringify(data)
        })
        const user = await response.json()
        return user
    }

    form.addEventListener('submit', async event => {
        event.preventDefault()
        const result = await updateUser({
            username: usernameField.value,
            email: emailField.value,
        })
    })
</script>
{% endblock %}

users/templates/users/user.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container">
        <div class="row no-gutters">
            <div class="col-12 col-sm-6 col-md-8">
                <div>
                    <h1>User: <b>{{ customer.username }}</b></h1>
                    <div class="card">
                        <div class="card-body">
                            <form id="user-info-form">
                                <div class="form-group">
                                    <label>Username</label>
                                    <input type="text" id="username-field" class="form-control" name="username" value="{{ customer.username }}">
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" id="email-field" class="form-control" name="email" value="{{ customer.email }}">
                                </div>
                                <button class="btn">Update</button>
                            </form>
                            <hr>
                            <form method="POST" action="{% url 'users:user_profile' customer.id %}">
                                {% csrf_token %}
                                <label>Rank:</label>
                                <select name="rank">
                                    {% for rank in userRanks %}
                                        <option value="{{ rank.id }}" {% if rank.id == customer.userprofile.userRank.id %}selected{% endif %}>
                                            {{ rank.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                                <button type="submit">Change rank</button>
                            </form>
                        </div>
                    </div>
                </div>

                <div>
                    <h2>Accounts associated with this user</h2>
                    <div class="list-group">
                        {% for account in accounts %}
                            <a href="{% url 'bank_accounts:accounts_show' account.id %}" class="list-group-item list-group-item-action">
                                {{account.name}}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        const endpoint = "/api/v1/users/{{ customer.id }}"
        const form = document.querySelector('#user-info-form')
        const usernameField = document.querySelector('#username-field')
        const emailField = document.querySelector('#email-field')

        function getCookie(name) {
            let cookieValue = null
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';')
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim()
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === name + '=') {
                        cookieValue = decodeURIComponent(
                            cookie.substring(name.length + 1)
                        )
                        break
                    }
                }
            }
            return cookieValue
        }

        const updateUser = async data => {
            const response = await fetch(endpoint, {
                method: 'PATCH',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken')
                },
                body: JSON.stringify(data)
            })
            const user = await response.json()
            return user
        }

        form.addEventListener('submit', async event => {
            event.preventDefault()
            const result = await updateUser({
                username: usernameField.value,
                email: emailField.value,
            })
        })
    </script>
{% endblock content %}

users/templates/users/users.html
{% extends "users/base.html" %}

{% block content %}
    <div class="container">
        <div class="row ">
            <div class="col-sm-6">
                <div>
                    <h1>Clients overview</h1>
                    <form method="GET">
                        <div class="active-cyan-4 mb-4">
                            <input class="form-control" id="user-search-input" type="text" placeholder="Search client..">
                        </div>
                    </form>

                    <br>

                    <ul class="list-group list-group-flush" id="user-list">
                        <p>Search for a user name above</p>
                    </ul>
                </div>

                <br>

                <div>
                    <h2>Create customers</h2>
                    <a class="btn btn-dark" href="{% url 'users:register' %}">Create customer</a>
                </div>
            </div>
        </div>
    </div>

    <template id="user-list-item-template">
        <li class="list-group-item"> 
            <a href="{% url 'users:user' user.id %}">Test</a>
        </li>
    </template>

    <script>
        const endpoint = "/api/v1/users/all"
        const userSearchInput = document.querySelector('#user-search-input')
        const userList = document.querySelector('#user-list')
        const userListItemTemplate = document.querySelector('#user-list-item-template')

        const fetchUsers = async query => {
            const response = await fetch(`${endpoint}?query=${query}`)
            const users = await response.json()
            return users
        }

        const renderUsers = users => {
            userList.innerHTML = ''

            users.forEach(user => {
                const node = userListItemTemplate.content.cloneNode(true)
                node.querySelector('a').innerHTML = user.username
                node.querySelector('a').setAttribute('href', `/users/${user.id}`)

                userList.appendChild(node)
            })
        }

        userSearchInput.addEventListener('input', async event => {
            event.preventDefault()
            const users = await fetchUsers(event.target.value)
            renderUsers(users)
            console.log(userList)
            console.log(userListItemTemplate)
        })
    </script>
{% endblock content %}