bankApp/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/users/login')),
    path('admin/', admin.site.urls),
    path('accounts/', include('bank_accounts.urls')),
    path('investments/', include('investments.urls')),
    path('users/', include('users.urls')),
    path('django-rq/', include('django_rq.urls')),
    #Api urls--
    path('api/v1/users/', include('users.endpoints')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

investments/urls.py
from django.urls import path

from . import views


app_name = "investments"

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('stocks/<str:ticker>', views.stock, name='stock'),
    path('stocks/<str:ticker>/buy', views.BuyView.as_view(), name='buy'),
    path('stocks/<str:ticker>/sell-all', views.SellAllView.as_view(), name='sell_all'),
    path('stocks/<str:ticker>/sell/<int:investment_id>', views.SellView.as_view(), name='sell'),
]

users/urls.py
from django.urls import path

from . import views

app_name='users'

urlpatterns = [
    path('', views.users, name='users'),
    path('<int:id>/', views.user, name='user'),
    path('<int:id>/profile', views.user_profile, name='user_profile'),
    path('home/', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

investments/models.py
from django.db import models
from djmoney.money import Money
from django.db.models import Sum
from djmoney.models.fields import MoneyField
from django.contrib.auth.models import User

class Stock(models.Model):
    name = models.CharField(max_length=250)
    ticker = models.CharField(max_length=250)

    @classmethod
    def find_by_ticker(cls, ticker):
        return cls.objects.get(ticker=ticker.upper())

    @classmethod
    def get_all(cls):
        return cls.objects.all()

    @classmethod
    def get_all_with_investments(cls, user):
        stocks = cls.get_all()
        stock_investments = []

        for stock in stocks:
            if stock.has_investment(user):
                stock.total_value = stock.get_total_value(user)
                stock.total_shares = stock.get_total_shares(user)
                stock_investments.append(stock)


        return stock_investments

    def record_price(self, price_as_string):
        return Price.create(self, Money(price_as_string, 'USD'))

    def get_history(self):
        return Price.get_history_by_stock(self)[:10]

    def has_investment(self, user):
        return bool(Investment.find_by_stock_and_user(self, user).count())

    def get_investments(self, user):
        return Investment.find_by_stock_and_user(self, user)

    def get_total_shares(self, user):
        return self.get_investments(user).aggregate(Sum('shares')).get('shares__sum')

    def get_total_value(self, user):
        return sum(investment.value for investment in self.get_investments(user))

    @property
    def price(self):
        return Price.get_latest_price_by_stock(self)

class Price(models.Model):
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    value = MoneyField(
        max_digits=14,
        decimal_places=2,
        default_currency='USD'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def create(cls, stock, value):
        price = cls()

        price.stock = stock
        price.value = value

        price.save()

        return price

    @classmethod
    def get_history_by_stock(cls, stock):
        return cls.objects.filter(stock=stock).order_by('-id')

    @classmethod
    def get_latest_price_by_stock(cls, stock):
        return cls.get_history_by_stock(stock).first()

    @classmethod
    def get_price_by_stock_and_time(cls, stock, timestamp):
        return cls.get_history_by_stock(stock).filter(created_at__lt=timestamp).first()

    def get_previous_price(self):
        return Price.objects.filter(stock=self.stock, id__lt=self.id).order_by('id').last()

    @property
    def formatted(self):
        return self.value

    @property
    def difference(self):
        previous_price = self.get_previous_price()

        if not previous_price:
            return Money(0, 'USD')

        return self.value - self.get_previous_price().value


class Investment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    shares = models.DecimalField(max_digits=19, decimal_places=10)
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def create(cls, user, stock, amount):
        investment = cls()

        investment.user = user
        investment.stock = stock

        shares = amount / stock.price.value.amount
        investment.shares = shares

        investment.save()

        return investment

    @classmethod
    def find_by_id(cls, id):
        return cls.objects.get(pk=id)

    @classmethod
    def find_by_user(cls, user):
        return cls.objects.filter(user=user)

    @classmethod
    def find_by_stock(cls, stock):
        return cls.objects.filter(stock=stock)

    @classmethod
    def find_by_stock_and_user(cls, stock, user):
        return cls.objects.filter(stock=stock).filter(user=user)

    def sell(self, amount):
        shares = amount / self.stock.price.value

        self.shares = self.shares - shares

        self.save()

    @property
    def value(self):
        return self.shares * self.stock.price.value

    @property
    def purchase_price(self):
        price = Price.get_price_by_stock_and_time(self.stock, self.created_at)

        return price.formatted

    @property
    def purchase_value(self):
        return self.shares * self.purchase_price
    

investments/forms.py
from django import forms
from bank_accounts.models import Account

class StockForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        accounts = Account.get_accounts(self.user).values_list('id', 'name')

        super(StockForm, self).__init__(*args, **kwargs)

        self.fields['account'].choices = [(None, 'Select')] + list(accounts)

class BuyStockForm(StockForm):
    account = forms.ChoiceField(
        label='Account',
        required=True,
        choices=()
    )
    amount = forms.IntegerField(
        label='Amount in dollars',
        required=True,
        min_value=1
    )


class SellStockForm(StockForm):
    account = forms.ChoiceField(
        label='Account',
        required=True,
        choices=()
    )
    amount = forms.FloatField(
        label='Amount in dollars',
        required=True,
        min_value=1
    )


class SellAllStockForm(StockForm):
    account = forms.ChoiceField(
        label='Account',
        required=True,
        choices=()
    )

investments/views.py
from django.shortcuts import render, redirect
from bank_accounts.models import Account
from .models import Stock, Investment
from . import forms
from django.views.generic import TemplateView
from django.contrib import messages
from djmoney.money import Money
from bank_accounts.models import Account, Transaction


def dashboard(request):
    context = {
        'stocks': Stock.get_all(),
        'stocks_with_investments': Stock.get_all_with_investments(request.user),
    }

    return render(request, 'investments/dashboard.html', context)

def stock(request, ticker):
    stock = Stock.find_by_ticker(ticker)

    context = {
        'stock': stock,
        'history': stock.get_history(),
        'investments': stock.get_investments(request.user),
        'total_shares': stock.get_total_shares(request.user),
        'total_value': stock.get_total_value(request.user)
    }

    return render(request, 'investments/stock.html', context)

class BuyView(TemplateView):
    def get(self, request, ticker):
        stock = Stock.find_by_ticker(ticker)

        context = {
            'form': forms.BuyStockForm(user=request.user),
            'stock': stock,
            'accounts': Account.get_accounts(request.user),
        }

        return render(request, 'investments/buy.html', context)

    def post(self, request, ticker):
        stock = Stock.find_by_ticker(ticker)
        form = forms.BuyStockForm(request.POST, user=request.user)

        if not form.is_valid():
            for key in form.errors:
                for error in form.errors[key]:
                    messages.error(request, f"{key}: {error}")
            return redirect('investments:buy', ticker=stock.ticker)

        data = form.cleaned_data
        account = Account.find_by_id(data.get('account'))
        amount = data.get('amount')

        Transaction.create_to_bank(account, amount, 'investment')
        Investment.create(
            request.user,
            stock,
            amount,   
        )
        messages.success(request, f"{stock.name} was purchased")

        return redirect('investments:dashboard')

class SellView(TemplateView):
    def get(self, request, ticker, investment_id):
        stock = Stock.find_by_ticker(ticker)
        investment = Investment.find_by_id(investment_id)

        context = {
            'form': forms.SellStockForm(user=request.user),
            'stock': stock,
            'investment': investment,
            'accounts': Account.get_accounts(request.user),
        }

        return render(request, 'investments/sell.html', context)

    def post(self, request, ticker, investment_id):
        stock = Stock.find_by_ticker(ticker)
        investment = Investment.find_by_id(investment_id)

        form = forms.SellStockForm(request.POST, user=request.user)

        if not form.is_valid():
            for key in form.errors:
                for error in form.errors[key]:
                    messages.error(request, f"{key}: {error}")
            return redirect('investments:buy', ticker=stock.ticker, investment_id=investment_id)

        data = form.cleaned_data
        account = Account.find_by_id(data.get('account'))
        amount = Money(data.get('amount'), 'USD')

        if amount > investment.value:
            amount = investment.value
            investment.delete()
        else:
            investment.sell(amount)

        Transaction.create_from_bank(account, amount, 'investment')
        messages.success(request, f"{stock.name} was sold")

        return redirect('investments:dashboard')

class SellAllView(TemplateView):
    def get(self, request, ticker):
        stock = Stock.find_by_ticker(ticker)

        context = {
            'form': forms.SellAllStockForm(user=request.user),
            'stock': stock,
            'accounts': Account.get_accounts(request.user),
            'total_value': stock.get_total_value(request.user),
        }

        return render(request, 'investments/sell-all.html', context)

    def post(self, request, ticker):
        stock = Stock.find_by_ticker(ticker)

        form = forms.SellAllStockForm(request.POST, user=request.user)

        if not form.is_valid():
            for key in form.errors:
                for error in form.errors[key]:
                    messages.error(request, f"{key}: {error}")
            return redirect('investments:sell_all', ticker=stock.ticker)

        data = form.cleaned_data
        account = Account.find_by_id(data.get('account'))
        investments = stock.get_investments(request.user)

        Transaction.create_from_bank(
            account,
            stock.get_total_value(request.user),
            'investment'
        )

        for investment in investments:
            investment.delete()

        messages.success(request, f"{stock.name} was sold")

        return redirect('investments:dashboard')

investments/templates/investments/buy.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <section>
                    <h2>Buy {{ stock.name }}</h2>
                    <div class="card" style="width: 30rem;">
                        <div class="card-body">
                            <p>
                                The current price is
                                <span 
                                    data-price 
                                    data-ticker="{{ stock.ticker | lower }}"
                                >
                                    {{ stock.price.formatted }}
                                </span>
                            </p>

                            {% url 'investments:buy' ticker=stock.ticker as action  %}
                            {% include 'investments/includes/form.html' with action=action cta="Buy" form=form %}
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    {% include 'investments/includes/live-view.html' with ticker=stock.ticker %}
{% endblock content %}

investments/templates/investments/dashboard.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <section>
                    <h2>My investments</h2>
                    <div class="card" style="width: 30rem;">
                        <div class="card-body">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Stock</th>
                                        <th>Shares</th>
                                        <th>Value</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% load has_investment %}
                                    {% for stock in stocks_with_investments %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'investments:stock' ticker=stock.ticker %}">
                                                    {{ stock.name }}
                                                </a>
                                            </td>
                                            <td>
                                                {{ stock.total_shares | floatformat:5 }}
                                            </td>
                                            <td
                                                data-total-value
                                                data-ticker="{{ stock.ticker }}"
                                            >
                                                {{ stock.total_value }}
                                            </td>
                                            <td>                                                    
                                                <a href="{% url 'investments:sell_all' ticker=stock.ticker %}">
                                                    Sell
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-sm-6">
                <section>
                    <h2>All stocks</h2>
                    <div class="card" style="width: 30rem;">
                        <div class="card-body">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Stock</th>
                                        <th>Current price</th>
                                        <th>Difference</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% load has_investment %}
                                    {% for stock in stocks %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'investments:stock' ticker=stock.ticker %}">
                                                    {{ stock.name }}
                                                </a>
                                            </td>
                                            <td data-price data-ticker="{{ stock.ticker | lower }}">
                                                {{ stock.price.formatted }}
                                            </td>
                                            <td data-difference data-ticker="{{ stock.ticker | lower }}">
                                                {{ stock.price.difference }}
                                            </td>
                                            <td>
                                                <a href="{% url 'investments:buy' ticker=stock.ticker %}">
                                                    Buy
                                                </a>
                                                {% has_investment stock as invested %}
                                                {% if invested %}
                                                    <a href="{% url 'investments:sell_all' ticker=stock.ticker %}">
                                                        Sell
                                                    </a>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    {% include 'investments/includes/live-view.html' with ticker="all" %}
{% endblock content %}

investments/templates/investments/sell-all.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <section>
                    <h2>Sell all {{ stock.name }} investments</h2>
                    <div class="card" style="width: 30rem;">
                        <div class="card-body">
                            <p>
                                The current price is
                                <span 
                                    data-price 
                                    data-ticker="{{ stock.ticker | lower }}"
                                >
                                    {{ stock.price.formatted }}
                                </span>
                            </p>
                            <p>
                                The current value of all your investments are 
                                <span 
                                    data-total-value
                                    data-ticker="{{ stock.ticker }}"
                                >
                                    {{ total_value }}
                                </span>
                            </p>

                            {% url 'investments:sell_all' ticker=stock.ticker as action  %}
                            {% include 'investments/includes/form.html' with action=action cta="Sell" form=form %}
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    {% include 'investments/includes/live-view.html' with ticker=stock.ticker %}
{% endblock content %}

investments/templates/investments/sell.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <section>
                    <h2>Sell {{ stock.name }}</h2>
                    <div class="card" style="width: 30rem;">
                        <div class="card-body">
                            <p>
                                The current price is
                                <span 
                                    data-price 
                                    data-ticker="{{ stock.ticker | lower }}"
                                >
                                    {{ stock.price.formatted }}
                                </span>
                            </p>
                            <p>
                                The current value is 
                                <span 
                                    data-total-value
                                    data-ticker="{{ stock.ticker }}"
                                >
                                    {{ investment.value }}
                                </span>
                                <button type="button" data-sell-all>
                                    Sell entire investment
                                </button>
                            </p>

                            {% url 'investments:sell' ticker=stock.ticker investment_id=investment.id as action  %}
                            {% include 'investments/includes/form.html' with action=action cta="Sell" form=form %}
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <script>
        const button = document.querySelector('[data-sell-all]')
        const input = document.querySelector('#id_amount')
        
        button.addEventListener('click', event => {
            const value = document.querySelector('[data-total-value]').textContent.trim().replace('$', '')
            input.value = value
        })
    </script>

    {% include 'investments/includes/live-view.html' with ticker=stock.ticker %}
{% endblock content %}

investments/templates/investments/stock.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container">
        <h2>{{ stock.name }}</h2>
        <div class="row">
            <div class="col-sm-6">
                <section class="page-section">
                    <h3>Info</h3>
                    <div class="card">
                        <div class="card-body">
                            <div class="kw-list">
                                <div>
                                    <span>Ticker:</span>
                                    <span>{{ stock.ticker }}</span>
                                </div>
                                <div>
                                    <span>Current price:</span>
                                    <span 
                                        data-price 
                                        data-ticker="{{ stock.ticker | lower }}"
                                    >
                                        {{ stock.price.formatted }}
                                    </span>
                                </div>
                                <div>
                                    <span>Difference:</span>
                                    <span 
                                        data-difference 
                                        data-ticker="{{ stock.ticker | lower }}"
                                    >
                                        {{ stock.price.difference }}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <div class="col-sm-6">
                <section class="page-section">
                    <h3>History</h3>
                    <div class="card">
                        <div class="card-body">
                            <div class="kw-list" data-history>
                                {% for price in history %}
                                    <div>
                                        <span>{{ price.formatted }}</span>
                                        <span>({{ price.difference }})</span>
                                    </div>
                                {% endfor %}
                            </div>
                            <template data-history-template>
                                <div>
                                    <span></span>
                                    <span></span>
                                </div>
                            </template>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <section class="page-section">
                    <h3>My investments</h3>
                    <div class="card">
                        <div class="card-body">
                            <div>
                                {% if investments %}
                                    <div class="mb-2">
                                        <h4>Total</h4>
                                        <div class="kw-list">
                                            <div>
                                                <span>Shares:</span>
                                                <span>{{ total_shares | floatformat:5 }}</span>
                                            </div>
                                            <div>
                                                <span>Current value:</span>
                                                <span 
                                                    data-total-value
                                                    data-ticker="{{ stock.ticker }}"
                                                >{{ total_value }}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mb-2">
                                        <h4>Investments</h4>
                                        {% for investment in investments %}
                                            <div class="mb-2">
                                                <h5>{{ investment.created_at }}</h5>
                                                <div class="kw-list">
                                                    <div>
                                                        <span>Purchase price:</span>
                                                        <span>{{ investment.purchase_price }}</span>
                                                    </div>
                                                    <div>
                                                        <span>Value at purchase:</span>
                                                        <span>{{ investment.purchase_value }}</span>
                                                    </div>
                                                    <div>
                                                        <span>Current value:</span>
                                                        <span 
                                                            data-investment
                                                            data-id="{{ investment.id }}"
                                                        >{{ investment.value }}</span>
                                                    </div>
                                                </div>
                                                <a href="{% url 'investments:sell' ticker=stock.ticker investment_id=investment.id %}">
                                                    Sell
                                                </a>
                                            </div>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    <p>You don't have any investments</p>
                                {% endif %}
                            </div>

                            <div>
                                <h4>Actions</h4>
                                <a href="{% url 'investments:buy' ticker=stock.ticker %}">
                                    Buy
                                </a>
                                {% if investments %}
                                    <a href="{% url 'investments:sell_all' ticker=stock.ticker %}">
                                        Sell all investments
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    {% include 'investments/includes/live-view.html' with ticker=stock.ticker %}
{% endblock content %}